In [1]:
type(100)

int

In [2]:
type(100.0)

float

In [3]:
type('dotmill')

str

In [4]:
type(['abc', 123])

list

In [5]:
type(('abc', 123))

tuple

In [6]:
dict_ex = {'name': 'kim', 'number': 100}

In [7]:
type(dict_ex)

dict

In [8]:
add_num = 1 + 1.0
print(add_num)
print(type(add_num))

2.0
<class 'float'>


In [9]:
float_num = 2.5
print("float_num", float_num)
print(type(float_num))

int_num= int(float_num)
print("int_num", int_num)
print(type(int_num))

float_num 2.5
<class 'float'>
int_num 2
<class 'int'>


In [10]:
print("Hello World", 2021)

Hello World 2021


In [11]:
print("Hello World" + 2021)

TypeError: can only concatenate str (not "int") to str

In [12]:
print("Hello World " + str(2021))

Hello World 2021


In [13]:
x=23.591
print('weight={0} kg'.format(x))

weight=23.591 kg


In [14]:
x=23.591
y=59
print('height={0}, weight={1} kg'.format(y, x))

height=59, weight=23.591 kg


In [15]:
print('height={0:5}, weight={1:.1f} kg'.format("hel", x))
print('height={0:05}, weight={1:.1f} kg'.format(y, x))
print('weight={0:5.1f}'.format(x))

height=hel  , weight=23.6 kg
height=00059, weight=23.6 kg
weight= 23.6


In [16]:
x_string="weight={0:5.1f}".format(x)
print(x)
print(x_string)
print(type(x_string))

23.591
weight= 23.6
<class 'str'>


In [17]:
list_ex = [1, 'abc', 1.07]

In [18]:
list_ex

[1, 'abc', 1.07]

In [19]:
list_ex[0]

1

In [20]:
len(list_ex)

3

In [21]:
list_ex.append(3.14)

In [22]:
len(list_ex)

4

In [23]:
del list_ex[0]
print(list_ex)

['abc', 1.07, 3.14]


In [24]:
list_ex.remove(1.07)
print(list_ex)

['abc', 3.14]


In [25]:
list_ex.pop()
print(list_ex)

['abc']


In [26]:
y = range(5, 10)

In [27]:
print(y)

range(5, 10)


In [28]:
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [29]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [30]:
a[1]

2

In [31]:
a[1] = 3

TypeError: 'tuple' object does not support item assignment

In [33]:
a = (1)
type(a)

int

In [34]:
a = (1,)
type(a)

tuple

In [35]:
dict_exam = {"이름": "김숭실", "주소": "상도로 369"}

In [36]:
dict_exam

{'이름': '김숭실', '주소': '상도로 369'}

In [37]:
print(dict_exam["이름"])

김숭실


In [38]:
print(dict_exam["주소"])

상도로 369


In [39]:
print(dict_exam.keys())

dict_keys(['이름', '주소'])


In [40]:
dict_exam2 = {"name": "김숭실", "addr": 369, "build": ["웨스트민스터홀", "벤처관"]}

In [41]:
dict_exam2

{'name': '김숭실', 'addr': 369, 'build': ['웨스트민스터홀', '벤처관']}

In [42]:
dict_in_dict = {"first": dict_exam, "second": dict_exam2}

In [43]:
dict_in_dict.keys()

dict_keys(['first', 'second'])

In [44]:
dict_in_dict["first"]

{'이름': '김숭실', '주소': '상도로 369'}

In [46]:
dict_in_dict["first"]["이름"]

'김숭실'

In [48]:
number_answer = 23
number_input = int(input())

if number_answer == number_input:
    print('정답')
else:
    print('오답')
print("프로그램 종료")

10
오답
프로그램 종료


In [49]:
number_answer = 23
number_input = int(input())

if number_answer == number_input:
    print('정답')

print("프로그램 종료")

10
프로그램 종료


In [50]:
number_1 = 10
number_2 = 12

if number_1 > number_2:
    print("number_1 이 number_2 보다 큽니다")
elif number_1 < number_2:
    print("number_2 가 number_1 보다 큽니다")
else:
    print("number_1 과 number_2 는 같습니다")
print("프로그램 종료")

number_2 가 number_1 보다 큽니다
프로그램 종료


In [51]:
sum = 0
i = 0

print("정수 입력")
input_number = int(input())

while i <= input_number:
    sum = sum + i
    i = i + 1
    
print("0 ~ {} 까지의 합은 {} 입니다.".format(input_number, sum))

정수 입력
10
0 ~ 10 까지의 합은 55 입니다.


In [52]:
sum = 0

print("정수 입력")
input_number = int(input())

for i in range(input_number+1):
    sum = sum + i
    i = i + 1
    
print("0 ~ {} 까지의 합은 {} 입니다.".format(input_number, sum))

정수 입력
10
0 ~ 10 까지의 합은 55 입니다.


In [53]:
num = [2,4,6,8,10]

for i in range(len(num)):
    num[i] = num[i]*2
    
print(num)

[4, 8, 12, 16, 20]


In [54]:
num = [2,4,6,8,10]

for i, n in enumerate(num):
    num[i] = n*2
    
print(num)

[4, 8, 12, 16, 20]


In [55]:
num = [2,4,6,8,10]
num_new = []

for n in num:
    num_new.append(n * 2)
    
print(num)

[2, 4, 6, 8, 10]


In [56]:
result = [1, 2] + [3, 4]

In [57]:
print(result)

[1, 2, 3, 4]


In [58]:
import numpy as np
np.__version__

'1.19.5'

In [59]:
x=np.array([1, 2, 3])
x

array([1, 2, 3])

In [60]:
print(x)

[1 2 3]


In [61]:
type(x)

numpy.ndarray

In [62]:
x.shape

(3,)

In [63]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [64]:
x[0]

1

In [65]:
y[2]

6

In [67]:
y[2] = 7
print(y)

[4 5 7]


In [68]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [69]:
a = np.array([1,1])
b=a
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('a=' + str(a))
print('b=' + str(b))

a=[1 1]
b=[1 1]
a=[100   1]
b=[100   1]


In [70]:
a = np.array([1,1])
b=a.copy()
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('a=' + str(a))
print('b=' + str(b))

a=[1 1]
b=[1 1]
a=[1 1]
b=[100   1]


In [71]:
list_x = [[1,2,3],[4,5,6]]
print(list_x)

[[1, 2, 3], [4, 5, 6]]


In [73]:
x = np.array(list_x)
print(x)

[[1 2 3]
 [4 5 6]]


In [76]:
print(x.shape)
print(type(x.shape))

(2, 3)
<class 'tuple'>


In [77]:
w, h = x.shape
print(w)
print(h)

2
3


In [78]:
print(x[1, 2])

6


In [79]:
matrix_zeros = np.zeros(5)
print("5 dimensional vector(1D array)")
print(matrix_zeros)
print("")

matrix_zeros = np.zeros((2,10))
print("2 x 10 matrix(2D array)")
print(matrix_zeros)
print("")

array3d_zeros = np.zeros((2,3,4))
print("2x3x4 3D array")
print(array3d_zeros)


5 dimensional vector(1D array)
[0. 0. 0. 0. 0.]

2 x 10 matrix(2D array)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

2x3x4 3D array
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [80]:
print(np.random.rand(2,3))

[[0.27483442 0.20541687 0.08545039]
 [0.51438023 0.93250757 0.84120842]]


In [81]:
print(np.random.randn(2, 3))

[[-0.14080889  0.5743982   0.04072751]
 [-0.92198701  0.07918772 -1.95496437]]


In [82]:
print(np.random.randint(1, 10, (2,5)))

[[7 5 1 5 2]
 [7 1 6 3 5]]


In [84]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
b = a.reshape(2, 5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [87]:
c = b.reshape(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [89]:
x = np.array([[4,4,4], [8,8,8]])
y = np.array([[1,1,1,], [2,2,2]])

print("x + y = \n", x+y)
print("x - y = \n", x-y)

x + y = 
 [[ 5  5  5]
 [10 10 10]]
x - y = 
 [[3 3 3]
 [6 6 6]]


In [90]:
print("10 * x =\n", 10 * x)

10 * x =
 [[40 40 40]
 [80 80 80]]


In [92]:
v = np.array([[1,2,3], [4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])

print("v*w=\n", v.dot(w))

v*w=
 [[14 14]
 [32 32]]


In [93]:
print(v*w)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [94]:
print(x * y)

[[ 4  4  4]
 [16 16 16]]


In [95]:
print(x / y)

[[4. 4. 4.]
 [4. 4. 4.]]


In [97]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [98]:
print(x[:5])

[0 1 2 3 4]


In [99]:
print(x[5:])

[5 6 7 8 9]


In [100]:
print(x[3:8])

[3 4 5 6 7]


In [101]:
print(x[3:8:2])

[3 5 7]


In [102]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [103]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("y=\n", y)
print("y[:2, 1:2]=\n", y[:2, 1:2])

y=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
y[:2, 1:2]=
 [[2]
 [5]]


In [104]:
x = np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [105]:
x[x>3]

array([ 5,  8, 13])

In [107]:
x[x>3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [108]:
def my_function_f(x):
    y = 3 * x + 4
    
    return y

result = my_function_f(3)

print(result)

13


In [109]:
def my_func3(input_array):
    mean = np.mean(input_array)
    std = np.std(input_array)
    
    return mean, std

In [110]:
data = np.random.randn(1000)
data_mean, data_std = my_func3(data)

print('mean: {0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean: -0.03, std:0.99


In [111]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)
data = []
print(data)
data = np.load('datafile.npy')
print(data)

[ 0.02201148  1.23129826 -0.85311274 -1.73398781  0.02370333]
[]
[ 0.02201148  1.23129826 -0.85311274 -1.73398781  0.02370333]


In [112]:
data1= np.array([1,2,3])
data2= np.array([10,20,30])
np.savez('datafile2.npz', data_first=data1, data_second=data2)
data1=[]
data2=[]
outfile = np.load('datafile2.npz')
print(outfile.files)

['data_first', 'data_second']


In [113]:
type(outfile)

numpy.lib.npyio.NpzFile

In [114]:
data1 = outfile['data_first']
data2 = outfile['data_second']

In [115]:
print(data1)
print(data2)

[1 2 3]
[10 20 30]
